name: build-groups-relay

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install lmdb dev
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get -o Acquire::Retries=10 -o Acquire::http::Timeout=60 -o Acquire::https::Timeout=60 update
          sudo apt-get -o Acquire::Retries=10 -o Acquire::http::Timeout=60 -o Acquire::https::Timeout=60 install -y --no-install-recommends liblmdb-dev

      - name: Build
        run: |
          go mod tidy
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-s -w" -o groups-relay .
          ls -la groups-relay

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: groups-relay
          path: groups-relay